swagger: "2.0"
info:
  title: "Spring Boot iTunes Microservice"
  version: "1.0"
  description: "Using the iTunes API lookup all albums and artists information"
host: "localhost:8035"
basePath: "/itunes"
schemes:
  - "http"
  - "https"
paths:
  /artists/{artistId}:
    get:
      tags:
        - "Album"
      summary: "Get all albums from an artist"
      operationId: "getAlbums"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#definitions/Album"
        "404":
          description: "Albums not found"
  /albums/{term}:
    get:
      tags:
        - "Artist"
      summary: "Get the 5 most relevant artists"
      operationId: "getArtists"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#definitions/Artist"
        "404":
          description: "Artists not found"
definitions:
  Album:
    type: "object"
    properties:
      albumId:
        type: "integer"
        format: "int64"
      albumName:
        type: "string"
      artist:
        type: "string"
      albumUrl:
        type: "string"
  Artist:
    type: "object"
    properties:
      artistId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      primaryGenreName:
        type: "string"
      artistLinkUrl:
        type: "string"
