spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:itunes_db;MODE=MySQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  hbm2ddl.auto: create

logging.level:
  com.manolitsas.david: debug



