server:
  port: 8035
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: healthcheck

feign:
  client:
    config:
      default:
        loggerLevel: FULL

itunes-client:
  name: itunesApi
  url: https://itunes.apple.com